# SCALE profile: production-grade. Requires Paid plan and multi-account (Organizations).
profile                    = "scale"
az_count                   = 3
enable_nat_gateway         = true
enable_vpc_interface_endpoints = true
compute_type               = "fargate"
ecs_min_healthy_percent    = 100
ecs_max_percent            = 200
db_engine                  = "aurora-postgresql"
db_multi_az                = true
db_reader_count            = 2
db_backup_retention_days   = 35
enable_rds_proxy           = true
cache_engine               = "valkey"
cache_node_type            = "cache.r7g.large"
cache_num_nodes            = 3
cache_multi_az             = true
enable_opensearch          = true
enable_waf                 = true
enable_mediaconvert        = true
use_secrets_manager        = true
use_customer_kms_keys      = true
enable_guardduty           = true
enable_container_insights  = true
enable_vpc_flow_logs       = true
log_retention_days         = 30
budget_alerts_usd          = [500, 1000, 2000]
aws_region                 = "ap-south-2"
cloudfront_cert_region     = "us-east-1"
edge_mode                  = "alb"
enable_alb                 = true
enable_video               = true
video_engine               = "mediaconvert_ap_south_1"   # MediaConvert is not in ap-south-2; alt: "ffmpeg_fargate"
grafana_mode               = "self_hosted"               # Managed Grafana not in ap-south-2
